### ISSUE TITLE
Forward refs

### ISSUE THREAD

**Issue by esseb** [nrkno/custom-element-to-react#16]
I'd like to send a `ref` prop to `@nrk/core-dialog` so I can e.g. do `getBoundingClientRect()` on the dialog element after it gets rendered by React, but in order to do that `@nrk/custom-element-to-react` needs to forward refs, see https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components

**Comment by esseb** [comment]
https://github.com/nrkno/custom-element-to-react/blob/master/lib/index.js already uses a ref internally, I'm not entirely sure how to do that and support an optionally forwarded ref prop simultaneously.

**Comment by eirikbacker** [comment]
Resolved by #49
