### ISSUE TITLE
Minifcation issues

### ISSUE THREAD

**Issue by eirikbacker** [nrkno/custom-element-to-react#29]
Terser causes `elementClass.name` to be optimized, and can therefore cause conflicts. See thread https://nrk.slack.com/archives/C49CY4VTP/p1562139748055000
Possible solution: add a UUID to `tagName` 👍

**Comment by piofinn** [comment]
I'd love to tackle this issue, as we're running into this bug in our production code!

I'm not sure where you use this function internally besides `core-components`, so it would be nice to know about any requirements for the API. My initial suggestion would be to add an optional `name` argument to the function (maybe in `options`?), and use a generated value if no name is passed. Would that work?

Also, do you have any preference regarding libraries for UUID? Or do you want to avoid external dependencies altogether?

**Comment by eirikbacker** [comment]
Outdated
